services:
  app:
    build: .
    container_name: character-text-generation

    volumes:
      - ./:/app
      - ./input:/app/input
      - ./results:/app/results
      - ./models:/app/models

    env_file:
      - .env

    working_dir: /app